[package]
name = "systemdetection"
version = "0.1.0"
edition = "2024"
description = "Far Cry 2 systemdetection.dll drop-in replacement"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]
name = "systemdetection"

[dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_SystemServices",
    "Win32_System_LibraryLoader",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
    "Win32_System_SystemInformation",
    "Win32_System_Registry",
    "Win32_System_Memory",
    "Win32_UI_WindowsAndMessaging",
]}
cppvtable = { git = "https://github.com/coconutbird/cppvtable.git" }
portex = "0.2"

[profile.release]
opt-level = 3
lto = true
strip = true
