name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install repository toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Prek checks
        uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0
        with:
          prek-version: "0.4.11"

      - name: Build
        run: cargo build --locked --release
